# Generated by Django 2.2.3 on 2019-08-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstoccurrence', models.DateTimeField()),
                ('node', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('alarm', models.TextField()),
                ('slug', models.SlugField(default='', null=True)),
                ('char', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
