# Generated by Django 2.2.3 on 2019-08-13 02:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(editable=False, verbose_name=datetime.datetime(2019, 8, 13, 2, 18, 56, 895095, tzinfo=utc)),
        ),
    ]
